
import { MantineProvider } from "@mantine/core";
import Script from "next/script";
import AppliIntegration from "@/components/AppliIntegration";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Banner from "@/components/Banner/Banner";
import Navbar from "@/components/Navbar/Navbar";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import React from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nagarjuna Degree College",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <appli-integration id="68afee1c37e33175ed91cb17"></appli-integration> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider>

          <main style={{ fontFamily: "Product Sans, sans-serif" }}>
            <Banner/>
            <Navbar/>
            <Header/>
            {children}
            <Footer/>
          </main>

          
          <Script
            src="https://www.appli.today/_next/static/bundle.js"
            strategy="afterInteractive"
          />
           <AppliIntegration />
        </MantineProvider>
      </body>
    </html>
  );
}
