
import { MantineProvider } from "@mantine/core";
import Script from "next/script";
import AppliIntegration from "@/components/AppliIntegration";
import { Analytics } from '@vercel/analytics/next';

import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

import Banner from "@/components/Banner/Banner";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import React from "react";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nagarjuna Degree College",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <appli-integration id="68afee1c37e33175ed91cb17"></appli-integration> */}
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider>

          <main className="font-sans">
            <Banner/>
            <Header/>
            {children}
            <Footer/>
          </main>

          
          <Script
            src="https://www.appli.today/_next/static/bundle.js"
            strategy="afterInteractive"
          />
           <AppliIntegration />
        </MantineProvider>
        <Analytics />
      </body>
    </html>
  );
}
